### ISSUE TITLE
Flutter 使用 scoped_model 合并 Model 时 发现mixin_inherits_from_not_object error

### ISSUE THREAD

**Issue by domliang** [domliang/blog#13]
### 错误内容
```bash
[Flutter/Dart] The class can’t be used as a mixin because it extends a class other than Object. Error [mixin_inherits_from_not_object]
```
### 解决方案：
```yaml
# pubspec.yaml
analyzer:
  strong-mod: true
  language:
    enableSuperMixins: true
```
```yaml
# analysis_options.yaml
analyzer:
  errors:
    mixin_inherits_from_not_object: ignore
```

### 参考资料

https://medium.com/@amandeepkochhar/flutter-dart-the-class-cant-be-used-as-a-mixin-because-it-extends-a-class-other-than-object-a53eb5f214b0
